name: Run Telegram Bot

on:
  push:
    branches:
      - main  # Запуск при изменениях в main
  schedule:
    - cron: "*/10 * * * *"  # Запуск раз в 10 минут (если бот выключился)
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ru_RU.UTF-8
          sudo update-locale LANG=ru_RU.UTF-8
          export LANG=ru_RU.UTF-8
          export LC_ALL=ru_RU.UTF-8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python bot.py
